services: 
  db: 
    image: mysql:8.0
    container_name: atm_mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
      - ./src/app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    secrets:
      - mysql_name
      - mysql_user
      - mysql_password
      - mysql_root_password
    environment:
      MYSQL_DATABASE: /run/secrets/mysql_name
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    ports: 
      - "3306:3306"
  
  app:
    build: ./src/app
    container_name: atm_app
    restart: always
    stdin_open: true # For interactive mode
    tty: true # Needed for curses to function properly
    depends_on:
      db:
        condition: service_healthy
    secrets:
      - mysql_user 
      - mysql_password
      - mysql_root_password
      - mysql_name
    environment:
      DB_HOST: db
      DB_NAME: /run/secrets/mysql_name
    volumes: 
      - ./src/app:/app
    entrypoint: ["/bin/bash", "./entrypoint.sh"]

secrets: 
  mysql_name: 
    file: ./src/secrets/mysql_name.txt
  mysql_root_password:
    file: ./src/secrets/mysql_root_password.txt
  mysql_password:
    file: ./src/secrets/mysql_password.txt
  mysql_user:
    file: ./src/secrets/mysql_user.txt  

volumes:
  db_data: 

