services: 
  app:
    build: .
    container_name: atm_app
    depends_on:
      - mysql
    # env_file: 
    #   - .env.developement
    environment: 
      DB_HOST: mysql
      # TERM: "xterm-256color"
    secrets:
      - db_user_password
    tty: true  # Needed for curses to function properly
    volumes: 
      - .:/app
    entrypoint: ["/bin/bash", "./entrypoint.sh"]

  mysql: 
    image: mysql:8.0
    container_name: atm_mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
      MYSQL_DATABASE: atm_db
      MYSQL_USER: atm_user
      MYSQL_PASSWORD: /run/secrets/db_user_password
    secrets:
      - db_root_password
      - db_user_password
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - "3306:3306"

secrets: 
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt

volumes:
  db_data: 